version: "3.7"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    entrypoint: sh
    command: -c 'mkdir -p /data/aoa && /usr/bin/minio server /data'

  aoa-core:
    image: thinkbiganalytics/aoa-demo:2.6.0
    container_name: aoa-core
    hostname: aoa-core
    restart: always
    environment:
      S3_EMBEDDED: "false"
      MODEL_ARTEFACT_REPO: s3
# if running on linux enter host ip address instead of host.docker.internal
      S3_HOST: http://host.docker.internal:9000
      S3_BUCKET: aoa
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      GIT_OFFLINE: "false"
      GIT_USERNAME: gituser
      GIT_PASSWORD: gitpassword
      VANTAGE_HOST: host.docker.internal
      VANTAGE_MODELS_DB: ivsm_user
      JAVA_OPTS: "-Dspring.flyway.locations=filesystem:/app/aoa/db/migration/h2/,filesystem:/app/aoa/db/demo-data/h2/"
    env_file:
      - ./aoa-core.env
    ports:
      - "8080:8080"
      - "61613:61613"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aoa-logs:/tmp/aoa-logs
      - /tmp/scheduler/dags/:/app/aoa/dags
    privileged: true

  aoa-ui:
    image: thinkbiganalytics/aoa-ui-demo:2.6.0
    container_name: aoa-ui
    hostname: aoa-ui
    restart: always
    ports:
      - "4200:4200"
      - "4201:4201"
    environment:
        START_LOCAL_LOGS_SERVER: "true" 
        LOG_MANAGEMENT_URL: "http://localhost:4201/$${JOB_ID}.log"
# if not running on local laptop change to the ip-address of the server
        BASE_URL: "http://localhost:8080/api"
        WEBSOCKET_URL: "ws://localhost:8080/tb-ml-websocket/websocket"
        SHOW_INFERENCE_WORKFLOW: "false"
    volumes:
      - /tmp/aoa-logs:/aoa-logs
    depends_on:
      - aoa-core

  gogs:
    image: thinkbiganalytics/aoa-demomodels:2.6.0
    container_name: demo-git
    hostname: demo-git
    ports:
      - "3000:3000"

  jupyter:
    image: thinkbiganalytics/aoa-jupyter:2.6.0
    container_name: jupyter
    env_file:
      - ./aoa-core.env
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.password='sha1:2513460e10c7:cbda35fc8e61514cebfe912ffb3b4330af5a49fa'

  demo-apps:
    image: nginx:alpine
    container_name: demo-apps
    ports: 
      - "8099:80"
    volumes:
      - ./websites:/usr/share/nginx/html

  airflow:
    image: thinkbiganalytics/aoa-airflow:2.6.0
    container_name: airflow
    ports: 
      - "9090:8080"
    environment:
      AIRFLOW__CORE__LOGGING_LEVEL: WARN
      GUNICORN_CMD_ARGS: "--log-level WARNING"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/scheduler/metadata:/scheduler
      - /tmp/scheduler/dags:/usr/local/airflow/dags
    privileged: true
    command: webserver

